services:

  db:
    container_name: database_sql
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~db:/var/lib/postresql/data
    env_file:
      - path: .env
        required: true

  api:
    container_name: Music_Lib_API
    build: .
    restart: always
    ports: 
      - 9000:9000
    env_file:
      - path: .env
        required: true