definitions:
  response.GetSongsResponse:
    properties:
      group:
        type: string
      id:
        type: string
      song:
        type: string
    type: object
  rest.APIError:
    properties:
      msg: {}
      status_code:
        type: integer
    type: object
host: localhost:9000
info:
  contact: {}
  title: Music Library API
  version: "1.0"
paths:
  /api/songs:
    get:
      description: Prints List of songs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.GetSongsResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.APIError'
      summary: Get Songs
      tags:
      - Songs
swagger: "2.0"
